{% set name = "libmagic" %}
{% set version = "5.33" %}
{% set hash_val = "1c52c8c3d271cd898d5511c36a68059cda94036111ab293f01f83c3525b737c6" %}

package:
  name: libmagic
  version: {{ version }}

source:
  fn: file-{{ version }}.tar.gz
  url: ftp://ftp.astron.com/pub/file/file-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - automake
    - autoconf
    - m4
    - libtool
    - {{ compiler('c') }}

test:
  commands:
    - "file --help &> /dev/null"
    - "test -r $CONDA_PREFIX/lib/libmagic.so"  # [linux]
    - "test -r $CONDA_PREFIX/lib/libmagic.dylib"  # [osx]
    - "conda inspect linkages -p $PREFIX $PKG_NAME"  # [linux]
    - "conda inspect objects -p $PREFIX $PKG_NAME"  # [osx]

about:
  home: http://www.darwinsys.com/file/
  summary: "Implementation of the file(1) command"
  license: BSD-2
  license_family: BSD
  license_file: COPYING

extra:
  recipe-maintainers:
    - mariusvniekerk
