travis:
  secure:
    BINSTAR_TOKEN: MisD1IStmVY6o57nSRzXOqiwdtos1PIwPAt5Ho0kaIGcxeyGxNo2zQj3vGwvOS6mvz/TlN30BjuY8rWKyBjfvS0iML1F507pXLLAudRryRX8KQjluYYmm7+qa7Enxb6/teifkxMB0CzICFrDpDXhl0AbgpuNFBFbAe+Uwaj6P3z80UlcuJsMuE881/bLfqj2c3XhQDibBub5OlzLbERwpok+7RQ2S93WTmfejkUYsawppZyj4iLpq90dZWtUbWZ08V3XAfeCg4CEuWdLsxidSf7g1GnwJ5Lw/cf4G/Xxij+FxhDkIYkMYKQ5GbcatJksjELjdX/yyI8xjGJ2jhDPcK54BuqmfdCsoX0TDfcnzDiWVOyYbz4sjx3x4vbXBJYQF98MnJbpUIoL5B8RwCtR/cs33HoJTm2dkXHMeXa+i+hudakTdoyZ5Z+OtpeF4vT6ZCDVIKTs+40bSXeoe9NRyHX28prIUuX8b9Ax2ye7AUvqOXKh/5/PW+qOfLjCET2EAneKVJ/xjnPvTIMxzxrEaKeGrMzrHOXDeeYjmq5TPUDs6krC9q2Uoxu9qKBWntedoUHU0IQcmzkoHlxZYzACOWnmOax5x0eU/rTjR1JUXYoY3QxKvNrIrYTDtnTfb/kJJnMVQVKhf0FEE+QYfNB0PqTSzwYkDjCd9YrWcc3espo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
