appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QADX8km5+RcWNSuVNG2jE9wgH2Q+XnosWDz2ogB3Dg8SGwyvTikMWpyLs62w986a8vcbTFo4+HVdMmPMI2Gexov6zWth45v3dfXit8Iw285oObGfOWEyfC539XdKJjFfM8VewTq7fiVxFdc5kbCwYGgkFU8ZpRKAbmYa7RV4nciniQUz9IBKk2KQsnOYt/WKQG/wJFpS/KoWBW+rYp51KQaEcHjLzvFocwuxeL79E+oTcIQk1RAr17bEjFJ9CkXFbwcbmeT07C+pn2SG1iLzshvHl4u1bLWostvVd5aAVljAY0FEwZEVm/6hNegnqB1RYxKAJUSJpW+g7ZDkY7E4VSNgTaydPGC2uCZIcpg4f+dVm6eQQGhDQkbRn7VSrPd4u3lwwBOn7W3LZ9SNb1uz2wKWIrPUgSFerX6crgG7in2b5iBWMgkueXPe0oiAWqnotP6vz9oWZWPbCl2lpzHmXTAiToV9fW/fT/yJytKLbR3HRyCWCyInT9/V9JvAJzDR4PpXsA/M/BUlgkzn1gLCDVngumLHFcDw12LoNY4EcOrOehRfDpPZOyiLymyDqnydaPa0osrEv7L+t4GiBgzSt3FbESqQmKcdkizZ2scYatl+Hx7YrlxRRLQBkoNGjwruyV7KN0C2BmhmVVEVVB6FdC5qXWydFzki9vDtagsLXY8=}
